### ISSUE TITLE
July 24, 2022 Issues

### ISSUE THREAD

**Issue by samuelchu90** [FleischerResearchLab/SALA#2]
-Get correct google time in Astral
-Sometimes we are 10min or 1 hour off on clockplots compared to prof Fleischer's clock plots
-To get correct sunrise and sunset times do something like this, where you do not specific timezone. This is because in our case latitude and longitude are not in same area as our timezone. ex: timezone: LA, coordinates: Seattle
`import datetime`
`from astral import LocationInfo, sun`
`#seattle coordinates`
`city = LocationInfo(47.61, 122.33)`
`#for 10/14/2015`
`date = datetime.datetime(2015, 10, 14)`
`sunrise = sun.sunrise(city.observer, date, tzinfo = city.tzinfo)`

Changed/Can push:
Ability to create grouped aka don't have to use group_by clockplots around line 108 of plots.py

**Comment by jasongfleischer** [comment]
Hey I just saw this issue, and note that it is still open and noody has responded.  Whats up @tktran11 and @samuelchu90?  Was this fixed or ignored?

**Comment by tktran11** [comment]
This was some wack problem I think that came up from Sam reading the data in from a csv (instead of a parquet file), because for some reason (unrelated to the other fastparquet issue) his fastparquet was not working. I did some testing later with astral to see how accurate it is to sunrise sunset times (by testing historical times from astral to google searches for sunset/sunrise for that day at the same location) and it seems fine at this point.
